language: java
install: true
os: linux
jdk:
- openjdk11
script:
- make ci
env:
  global:
  - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS=true
  - PACT_BROKER_BASE_URL=https://test.pactflow.io
  - PACT_BROKER_HOST=test.pactflow.io